name: 🔄 Integration

on:
  pull_request:

jobs:
  linelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for 1. missing end line breaks and 2. control characters in filenames
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          success=true

          # 줄바꿈 체크
          echo "## 줄바꿈 누락 파일" >> $GITHUB_STEP_SUMMARY
          for file in $files; do
            if [ -s "$file" ] && [ "$(tail -c 1 $file | wc -l)" -eq 0 ]; then
              echo "- $file" >> $GITHUB_STEP_SUMMARY
              success=false
            fi
          done

          # 제어문자 체크
          echo -e "\n## 제어문자가 포함된 파일명" >> $GITHUB_STEP_SUMMARY
          for file in $files; do
            if [ -e "$file" ]; then  # 파일이 존재하는 경우만 체크
              clean_name=$(printf '%q' "$file")
              if [ "$file" != "$clean_name" ]; then
                echo "- $file" >> $GITHUB_STEP_SUMMARY
                success=false
              fi
            fi
          done

          if [ "$success" = false ]; then
            echo -e "\n:warning: 위 문제들을 해결해 주세요:" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi